export const HTTP_PROXY = "http://127.0.0.1:33210";

export const CATEGORIES = [
  { value: "Academic", emoji: "🎓", weight: 80 },
  { value: "AI", emoji: "✨", weight: 100 },
  { value: "Arts", emoji: "🎨" },
  { value: "Automotive", emoji: "🚗" },
  { value: "Blog", emoji: "📝" },
  { value: "Business", emoji: "💼", weight: 70 },
  { value: "Culture", emoji: "🌍" },
  { value: "DIY & Crafts", emoji: "🔨" },
  { value: "Economics", emoji: "💹", weight: 80 },
  { value: "Education", emoji: "📚" },
  { value: "Entertainment", emoji: "🎭" },
  { value: "Environment", emoji: "🌱" },
  { value: "Finance", emoji: "💰", weight: 80 },
  { value: "Gaming", emoji: "🎮" },
  { value: "General", emoji: "🌞", weight: 90 },
  { value: "Health", emoji: "💊" },
  { value: "History", emoji: "📜" },
  { value: "Language", emoji: "🔤" },
  { value: "Legal", emoji: "🧑‍⚖️" },
  { value: "Lifestyle", emoji: "🛋️" },
  { value: "Other", emoji: "💭" },
  { value: "Personal Development", emoji: "🚀", weight: 85 },
  { value: "Philosophy", emoji: "🤔" },
  { value: "Politics", emoji: "🏛", weight: 80 },
  { value: "Product", emoji: "📱", weight: 85 },
  { value: "Programming", emoji: "💻", weight: 85 },
  { value: "Psychology", emoji: "🧠", weight: 80 },
  { value: "Real Estate", emoji: "🏠" },
  { value: "Religion", emoji: "⛪" },
  { value: "Science", emoji: "🔬", weight: 80 },
  { value: "Social Media", emoji: "💬" },
  { value: "Sports", emoji: "⚽" },
  { value: "Startup", emoji: "🚀", weight: 90 },
  { value: "Technology", emoji: "🤖", weight: 90 },
  { value: "Travel", emoji: "🛫" },
];

export const PLAIN_CATEGORIES = CATEGORIES.map((category) => category.value);
